name: Benchmark this PR
on:
  pull_request:
    branches: [ main ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"
          job-summary: "true"
          bench-on: ${{ github.event.pull_request.head.sha }}
